### ISSUE TITLE
dateStarted and dateCompleted field from patient model needs to be handled

### ISSUE THREAD

**Issue by poojaRal** [promisasu/Portal#100]
After the enhancement from issue #99, dateStarted field must be saved with the user input passed.
dateCompleted field must be auto-populated by calculating as below -

Each trial in which the patient is getting enrolled has a duration field.
dateCompleted for a patient must be populated as per his dateStarted column + duration of the trial enrolled in.

This needs to be done when the patient is getting created.

**Comment by ChristianMurphy** [comment]
resolved on current `master` branch
