### ISSUE TITLE
IRB Start and End dates are off by 1 day

### ISSUE THREAD

**Issue by sylvr3** [promisasu/Portal#108]
When adding a new trial, the start and end dates are 1 day behind in the table from what the user has inputted into the add-trial modal. (For instance, in the example screenshots below, the dates in table should be November 20th and November 27th):

![screenshot from 2015-11-20 10 22 23](https://cloud.githubusercontent.com/assets/1154846/11306715/e1125138-8f70-11e5-8624-cfe412eebbd7.png)
![screenshot from 2015-11-20 10 22 39](https://cloud.githubusercontent.com/assets/1154846/11306716/e118f164-8f70-11e5-9dc6-3a0fd7c86109.png)

**Comment by ChristianMurphy** [comment]
resolved by #207
