### ISSUE TITLE
All chart data should pull from DB

### ISSUE THREAD

**Issue by beccannlittle** [promisasu/Portal#117]
Remember when I was talking about having a 'graceful empty state'? Charts are currently not hooked up to DB, so there will be no empty states.

**Comment by ChristianMurphy** [comment]
So would a graceful empty state be an empty graph or a message something like what is [used for the tables](https://github.com/ser515asu/PRP-Manhattan-Project/pull/30#issuecomment-148865843)?

**Comment by ChristianMurphy** [comment]
Resolved on current `master`
