### ISSUE TITLE
IMS Question and Test Interoperability 2.2

### ISSUE THREAD

**Issue by ChristianMurphy** [promisasu/Portal#170]
Questions and Scoring could be implemented using IMS Question and Test Interoperability (QTI) 2.2
Which is a standard for how to write questions and scoring using XML.
_NOTE_: IMS QTI is format, actual rendering and scoring logic would still need to be implemented.

**Pros**
- IMS QTI has formats for all of the existing question types
- IMS QTI would allow for a variety of new question types
- IMS QTI offers a way to represent scoring

**Cons**
- IMS QTI currently only supports XML, no JSON support

**Implementation Notes**
- Questions could be rendered with [XSL Transforms](http://www.w3schools.com/xsl/)
- Node JS requires a shim to process XML server side, there are a few options:
  - [libxmljs](https://github.com/polotek/libxmljs) - Fast standardized library, currently does not work on windows 10
  - [jsdom](https://github.com/tmpvar/jsdom) - Technically an HTML parser can also do some XML
  - [electron](https://github.com/atom/electron) - Runs Chromium (open source Chrome) on top of Node JS

reference https://www.imsglobal.org/question/qtiv2p2/imsqti_v2p2_impl.html

**Comment by ChristianMurphy** [comment]
@chintanallstarz this research was requested by @kgary I would consult with him before closing.

**Comment by chintanallstarz** [comment]
Dr Gary is sitting next to me. 

Don't you have a job ?
-K Gary
