### ISSUE TITLE
IOS device is not able to get a survey for any PIN using new API

### ISSUE THREAD

**Issue by poojaRal** [promisasu/Portal#228]
On an IOS device, if we put it in the server address as "swent1linux.asu.edu:3001" and a PIN which is active in the portal, it is not able to get a survey.

**Comment by ChristianMurphy** [comment]
It is possible this could be a [Mixed Content](https://developer.mozilla.org/en-US/docs/Security/Mixed_content) issue.
Most browsers now try to block any http connections if the main connection is https.

**Comment by poojaRal** [comment]
This has been fixed by adding http connection properties in info.plist in the iOS code. Tested successfully.
