### ISSUE TITLE
On New patient enrollment for SCD trial, first weekly survey duration is set for 3 days instead of 2 days

### ISSUE THREAD

**Issue by poojaRal** [promisasu/Portal#250]
On Enrolling a  new patient for SCD trial,
For eg:
Patient start date - 02-26-2016
Patient end date - 04-01-2016 (after 5 weeks)

The first weekly survey instance gets generated in the system.
Survey instance start time : 02-26-2016
Survey instance end time : 02-28-2016

Expected Result : Survey instance end Time : 02-27-2016

**Comment by ChristianMurphy** [comment]
Help me understand this.

I thought that Weekly surveys were given 1 day + 1 day grace period.
Meaning that the 28th would be the correct end date for this survey.

What is the expected logic for a weekly survey?

**Comment by poojaRal** [comment]
If the survey start date is 26th then adding 1 more day to it, survey end date should be 27th. However it's showing 28th as end date

**Comment by ChristianMurphy** [comment]
Okay, what about the 1 day grace period for weekly surveys?

**Comment by poojaRal** [comment]
As per my understanding the calculation is as below -
For example -
1. The patient gets enrolled on 26th at 3.00 PM
So the first survey instance gets created on the same day with start date as 26th.
Hence for weekly survey logic - 26th is the 1st day and 1 day grace period gets added to it.
So 26 + 1 day is 27th. 
2. Hence the patient's first survey instance must have end date as 27th and this particular survey instance must be valid only till 27th midnight.

Please correct me if I am wrong here.

**Comment by ChristianMurphy** [comment]
The way I understood it 1 day and 1 day grace means.
26 + 1 + 1 = 28
Which matches the existing implementation.

**Comment by poojaRal** [comment]
@kgary Could you please have a look over this issue and let us know which understanding is correct?
Me and @ChristianMurphy are not on the same page I guess.

**Comment by poojaRal** [comment]
Duration of weekly survey instances are calculated from midnight to midnight.
That means if the patient got enrolled on 26th Feb then his 2 days period for weekly survey instance is calculated as:

1st day as - 26th Feb 00:00:00 to 27th Feb 00:00:00
2nd day as - 27th Feb 00:00:00 to 28th Feb 00:00:00

Hence the end time for weekly survey instances shows as 28th Feb.

This is correct and expected behavior.
This issue has been discussed and resolved.
