### ISSUE TITLE
Weekly survey instance submission date not shown correct in the portal

### ISSUE THREAD

**Issue by poojaRal** [promisasu/Portal#251]
For a SCD trial patient, first weekly survey instance is generated on enrollment.
As per issue #250: 

Survey Instance start time : 02-26-2016
Survey Instance end time : 02-28-2016
Survey is taken on the app on system date : 02-26-2016

Expected Result : Submisison time : 02-26-2016

Actual : Submission time is set as : 02-27-2016

**Comment by ChristianMurphy** [comment]
What is the date stored as in the database?

**Comment by poojaRal** [comment]
The date being stored in the database is also 27th Feb. 
User submission time - is collected from the app when the survey is submitted.
Actual submission time - is calculated in the API handling before saving the survey instance as completed.

Both are pointing to the same date as "27th Feb".

**Comment by ChristianMurphy** [comment]
related to #217

**Comment by mpenumal** [comment]
The user story associated with this defect was done today.
@ChristianMurphy @poojaRal : Can we close this based on that?

**Comment by poojaRal** [comment]
Right now we have GMT time in the entire portal application? At least we are sure that there is one common timezone which we are following in the whole application.

**Comment by mpenumal** [comment]
Yes... GMT while saving in DB.

**Comment by poojaRal** [comment]
We will discuss this on Monday and then close the issue if required.

**Comment by poojaRal** [comment]
This has been resolved and merged to master.
