### ISSUE TITLE
Proxying https into node staging and demo

### ISSUE THREAD

**Issue by kgary** [promisasu/Portal#295]
Currently we are running 4 node services on swent1linux, 2 for staging (api and portal) and 2 for demo (same). We'd like to put https in front to comply with ASU policies, and proxy URLs to the right ports so we can make use of familiar http and https without port numbers on URLs. One solution is to put Apache http in front on port 443, but this has challenges - the standard mod_rewrite rules don't work well for the portal, and Apache's multithreaded architecture in front of Node's kinda defeats the purpose (though we won't have a scale issue). 
Node has some rogue modules that claim to do the proxying, reverse-proxying and rewrites, but these are not supported packages, just things from various websites and GH repos. It seems best to use port 443 for https traffic to demo, and 444 for https traffic to staging. We will just have to remember that staging requires the port number.

**Comment by ChristianMurphy** [comment]
I'm not entirely clear on what the question is here. :confused: 

For adding https there are a few options:

**Apache URL Rewrite**
_Pros_: Fast
_Cons_: This would require a rewrite of all template code to include the server prefix so pages route correctly.

**Apache Port Forward**
_Pros_: Fast and Easy
_Cons_: Each server will still need a separate port.

**Node Rewrite Modules**
_Pros_: Its JavaScript ¯\_(ツ)_/¯
_Cons_: Slower than Apache, Often less documented and more complicated than Apache

**Node HTTPS**
_pros_: built into NodeJS and `hapi`
_cons_: node needs to know where the certificate and key `pem` files are

I would personally recommend using Apache to forward ports, or adding HTTPS directly to NodeJS.

**Comment by kgary** [comment]
The questions, or enhancements, needed here is 1) we'd like to avoid URLs with port numbers in them, at least for CNHS guests, and 2) as per ASU policies we need to be running under HTTPS. I could have written these as 2 issues. Apache URL rewrite is the typical way I would do this, and I did start to do this, but a) I am having trouble with the reverse-proxy rewrite rules (the CSS wasn't coming through), and 2) I read it is considered poor practice to do this because you are putting a worker-thread implementation in front of your asynchronous single-thread implementation, thereby defeating the point of the latter. I don't see how Apache port forwarding helps us (and you can port forward better through iptables) or Node rewrite. Node HTTPS is possible and the implementation looks easy. But it only solves 2 and not 1.

I guess I should just go debug the Apache rewrite rules...

**Comment by ChristianMurphy** [comment]
Addressing the ports, we can change the demo dashboard to default to port 80 or 443.
Because of the design desision to have api and portal as separate servers, we can't have the api and the portal both on the same port without a rewrite.

If we do go with rewrite, the [dashboard router](https://github.com/promisasu/Portal/blob/master/controller/router.js) and [api router](https://github.com/promisasu/Portal/blob/master/api/router.js) have a complete description of all paths that the application uses. :100: 

Addressing HTTPS it is simple to add to NodeJS, but if we know we are going to have a rewrite or reverse proxy I would rather that handle the HTTPS than NodeJS.

**Comment by kgary** [comment]
I tried rewrites in Apache but then I realized the app has no mechanism to add a relative path to an endpoint, it just takes a server:port and a protocol (enhancement needed). I then tried modifying controller/server.js but I was guessing as there is no documentation I could find on configuring https on their website or that I could find (I tried configuring tls property based on a stackoverflow post, epic fail. Of course, nothing in the log, no error message anywhere, just fail. Yay!). 

So at this point I just wanted to leave staging where it is and change demo to use port 80. Except that I couldn't run the server under sudo for promis since I don't know the account's password.

Going forward, what we should do is running staging over https on port 4443, and demo over https on 443. Port 80 should be redirected to 443. Apache has been shut off so node can use these ports without conflict.

**Comment by ChristianMurphy** [comment]
> no documentation I could find on configuring https on their website or that I could find

It is there, they named it `tls` instead of `https`
http://hapijs.com/api#serverconnectionoptions

> Of course, nothing in the log, no error message anywhere, just fail. Yay!

The portal is designed to handle error similar to Apache, it is written to a log file.
The log file is stored in the `logs/` folder under the project home.
The logs can also be viewed using `npm run log`

> Going forward, what we should do is running staging over https on port 4443, and demo over https on 443

Will do
