### ISSUE TITLE
Patient CSV export data is incorrect for the body Pain question.

### ISSUE THREAD

**Issue by poojaRal** [promisasu/Portal#308]
**What did you do?**
Exported a patient's data in csv format from the portal
**What did you expect to happen?**
Patient data to be exportted in the required format with all questions and selected question options in it.
**What actually happened?**
For the body Pain question when the selected answer is "No Pain" then the format is incorrect.
![image](https://cloud.githubusercontent.com/assets/12092237/13936010/0ab854b2-ef78-11e5-9401-e6f4f494582f.png)
After question 31 we need to have one blank line for the two-part question to be displayed correctly.
Whereas we have a blank line after the question 1 which is wrong.

**Comment by ChristianMurphy** [comment]
Confirmed this issue,
it appears to be specific to body pain questions where `none` is the selected option.
If an area and a severity are selected the spreadsheet is correct.

![working](https://cloud.githubusercontent.com/assets/3107513/13993209/a72f9084-f0dc-11e5-89e1-dcb4ec55a387.PNG)

**Comment by poojaRal** [comment]
Issue is with the way query is returning data from SQL in order to display data on the individual survey results page as well. Similar issue is present with the export as well.
![image](https://cloud.githubusercontent.com/assets/12092237/13995950/d0961a86-f0e8-11e5-8569-e4708fdac3b3.png)

**Comment by ChristianMurphy** [comment]
Hmmm
looking at the local storage I'm not sure where 'never' is coming from.
![working value](https://cloud.githubusercontent.com/assets/3107513/13997074/951e7bb0-f0ed-11e5-8c8d-7c93d03ff4b4.PNG)
![broken value](https://cloud.githubusercontent.com/assets/3107513/13997073/951e6742-f0ed-11e5-829f-38784d7670f3.PNG)
