### ISSUE TITLE
Firefox browser not rendering the fields proper on MAC Mini

### ISSUE THREAD

**Issue by poojaRal** [promisasu/Portal#311]
**What did you do?**
On Mac Mini, started the portal on swent1linux,asu.edu:4000 and clicked on "Enroll  a new patient"
**What did you expect to happen?**
The fields are supposed to be rendered as per the screen size
**What actually happened?**
The fields are not rendered as per the screen size.

![screen shot 2016-03-23 at 2 41 25 pm](https://cloud.githubusercontent.com/assets/12092237/14002044/8ce9d91c-f106-11e5-928d-e8819a1ab92c.png)

**Comment by ChristianMurphy** [comment]
This issue was on Firefox correct?
Do you know which version of Firefox was used?
