### ISSUE TITLE
PRP shows semi-compliant when it should show non-compliant

### ISSUE THREAD

**Issue by kgary** [promisasu/Portal#314]
When reviewing the PRP staging portal, I notice several test ids in the 200x range now have 2 expired surveys but yet these PINs are shown as being "semi-compliant" instead of "non-compliant". For example, see PIN 2004

**Comment by ChristianMurphy** [comment]
Please use the issue template in the future

**Comment by ChristianMurphy** [comment]
Currently the metric looks at a 1 week period.
Within that period

0 expired = compliant
1 expired = semi-compliant
2+ expired = non-compliant

The compliance level you mentioned is correctly reflecting the current metric.

As always we are open to suggestions for metrics that would better reflect compliance. :smile: 

references:
https://tree.taiga.io/project/promisasu-prp-manhattan-project/us/1
https://github.com/promisasu/Portal/blob/master/controller/helper/process-compliance-count.js#L20-L29

**Comment by kgary** [comment]
I'm confused as to how you can be non-compliant with 2+ expired in a 1 week period if you are only asked to do 1 survey in a 1 week period

Let's use this rule:
>= 80% compliant
>= 50% semi-compliant
< 50% non-compliant

**Comment by shahsyedzafar** [comment]
Fine. I will go by this rule and make the changes in the query

**Comment by kgary** [comment]
When I asked for this to be implemented I wanted a strategy pattern done so we could swap out the algorithm or customize without a code change

**Comment by ChristianMurphy** [comment]
@kgary 
> Let's use this rule:
>
> > = 80% compliant
> > = 50% semi-compliant
> > < 50% non-compliant

Sounds good to me. :smile: 

Some clarifications on this:
1. For the donut chart should this use time or number of surveys to filter?
2. What should be the default filter? (All surveys, past 1 month, past 10 surveys)

> When I asked for this to be implemented I wanted a strategy pattern done so we could swap out the algorithm or customize without a code change

The ground work is in place, we have the interface needed. :+1: 
It just needs to be completed and tested. :sparkles: 

Another clarification:
3. Where should the strategy be set? (Should there be a field in the db storing it, should there be a dropdown on each view allowing strategy to be set? Is there another way?)

**Comment by ChristianMurphy** [comment]
@shahsyedzafar 

> Fine. I will go by this rule and make the changes in the query

The query will be the same.
[`process-compliance-count.js`](/promisasu/Portal/blob/master/controller/helper/process-compliance-count.js) and [`process-patient-status.js`](/promisasu/Portal/blob/master/controller/helper/process-patient-status.js) will need to change.

reference:
https://en.wikipedia.org/wiki/Strategy_pattern
http://www.dofactory.com/javascript/strategy-design-pattern
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes

**Comment by mohitkm** [comment]
The current SCD Portal uses a different logic for determining Compliance. We have: -
1) Patients who have completed two-thirds or more of their activities are considered Compliant.
2) Patients who have completed between one-third and two-thirds of their activities are considered Partially-Compliant/Semi-compliant
3) Patients who have completed less than one-third of their activities are considered Non-compliant.


The commit is  here Completed semi compliance computation and cleaned up the trial page -…
