### ISSUE TITLE
Cannot retrieve survey instance

### ISSUE THREAD

**Issue by kgary** [promisasu/Portal#315]
Test environment: staging

In trying to test the app, I cannot seem to use any existing PINs on staging as there are none with pending surveys. So I enrolled a new patient (2013) in SCD. But when using this PIN and connecting the APi to swent1linux.asu.edu:40001 (https or http) I get no survey. not even an error message. Just "To configure PIN and server settings, please click on Settings button:"

**Comment by kgary** [comment]
Relevant info from logs (does anyone ever check the logs while running?):

03-26 15:16:47.516 13305-13305/org.cnmc.painClinic I/chromium: [INFO:CONSOLE(11706)] "SyntaxError: Unexpected token 
03-26 15:16:47.519 13305-13305/org.cnmc.painClinic I/chromium: [INFO:CONSOLE(11706)] "TypeError: Cannot read property 'method' of undefined
                                                                   at responseError (file:///android_asset/www/scripts/app.js:1:653)
                                                                   at processQueue (file:///android_asset/www/lib/angular.min.js:13318:27)
                                                                   at file:///android_asset/www/lib/angular.min.js:13334:27
                                                                   at Scope.$eval (file:///android_asset/www/lib/angular.min.js:14570:28)
                                                                   at Scope.$digest (file:///android_asset/www/lib/angular.min.js:14386:31)
                                                                   at Scope.$apply (file:///android_asset/www/lib/angular.min.js:14675:24)
                                                                   at done (file:///android_asset/www/lib/angular.min.js:9725:47)
                                                                   at completeRequest (file:///android_asset/www/lib/angular.min.js:9915:7)
                                                                   at XMLHttpRequest.requestLoaded (file:///android_asset/www/lib/angular.min.js:9856:9)", source: file:///android_asset/www/lib/angular.min.js (11706)
03-26 15:16:47.520 13305-13305/org.cnmc.painClinic I/chromium: [INFO:CONSOLE(1)] "Unable to get release number from local config.", source: file:///android_asset/www/scripts/controllers/settingsController.js (1)
03-26 15:17:01.086 13305-13305/org.cnmc.painClinic D/cr_Ime: [ImeAdapter.java:553] focusedNodeChanged: isEditable [false]
03-26 15:17:01.101 13305-13305/org.cnmc.painClinic I/chromium: [INFO:CONSOLE(1)] "false", source: file:///android_asset/www/scripts/app.js (1)
03-26 15:17:01.118 13305-13305/org.cnmc.painClinic W/cr_BindingManager: Cannot call determinedVisibility() - never saw a connection for the pid: 13305
03-26 15:17:01.146 13305-13305/org.cnmc.painClinic D/cr_Ime: [ImeAdapter.java:553] focusedNodeChanged: isEditable [false]
03-26 15:17:01.150 13305-13305/org.cnmc.painClinic I/chromium: [INFO:CONSOLE(1)] "false", source: file:///android_asset/www/scripts/app.js (1)
03-26 15:17:01.152 13305-13305/org.cnmc.painClinic W/cr_BindingManager: Cannot call determinedVisibility() - never saw a connection for the pid: 13305
03-26 15:17:01.212 13305-13305/org.cnmc.painClinic D/cr_Ime: [ImeAdapter.java:253] updateKeyboardVisibility: type [0->0], flags [0], show [true], 
03-26 15:17:01.213 13305-13305/org.cnmc.painClinic D/cr_Ime: [ImeAdapter.java:326] hideKeyboard
03-26 15:17:01.213 13305-13305/org.cnmc.painClinic D/cr_Ime: [InputMethodManagerWrapper.java:56] isActive: true
03-26 15:17:01.214 13305-13305/org.cnmc.painClinic D/cr_Ime: [InputMethodManagerWrapper.java:65] hideSoftInputFromWindow
03-26 15:17:01.364 13305-13305/org.cnmc.painClinic I/chromium: [INFO:CONSOLE(1)] "true", source: file:///android_asset/www/scripts/app.js (1)
03-26 15:17:01.364 13305-13305/org.cnmc.painClinic I/chromium: [INFO:CONSOLE(1)] "-1", source: file:///android_asset/www/scripts/app.js (1)
03-26 15:17:01.374 13305-13305/org.cnmc.painClinic I/chromium: [INFO:CONSOLE(1)] "-1", source: file:///android_asset/www/scripts/controllers/homeController.js (1)
03-26 15:17:01.374 13305-13305/org.cnmc.painClinic I/chromium: [INFO:CONSOLE(1)] "unknownError", source: file:///android_asset/www/scripts/controllers/homeController.js (1)

**Comment by kgary** [comment]
Just tried it on a 2nd tablet. I see this in the logs, which makes me think that whatever we are using for the cert on swent1linux is incorrect - I had this chaining issue before.

`03-26 15:48:06.005 32624-822/org.cnmc.painClinic D/OpenSSLLib: OpensslErr:Module:13(114:155); file:external/openssl/crypto/asn1/asn1_lib.c ;Line:142;Function:ASN1_get_object
03-26 15:48:06.052 32624-822/org.cnmc.painClinic I/X509Util: Failed to validate the certificate chain, error: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
03-26 15:48:06.072 32624-32624/org.cnmc.painClinic D/AwContents: setContentsSize 600, 951
03-26 15:48:06.072 32624-32624/org.cnmc.painClinic D/AwContents: setPageScaleFactor 1.0
03-26 15:48:06.073 32624-32624/org.cnmc.painClinic D/OpenSSLLib: OpensslErr:Module:13(114:155); file:external/openssl/crypto/asn1/asn1_lib.c ;Line:142;Function:ASN1_get_object`

**Comment by kgary** [comment]
Another update, I tried lead6 to see if it was a server-side cert issue and apparently it is:

`03-26 15:59:00.227 32624-2996/org.cnmc.painClinic D/OpenSSLLib: OpensslErr:Module:13(114:155); file:external/openssl/crypto/asn1/asn1_lib.c ;Line:142;Function:ASN1_get_object
03-26 15:59:00.231 32624-2996/org.cnmc.painClinic D/OpenSSLLib: OpensslErr:Module:13(114:155); file:external/openssl/crypto/asn1/asn1_lib.c ;Line:142;Function:ASN1_get_object
03-26 15:59:00.232 32624-2996/org.cnmc.painClinic D/OpenSSLLib: OpensslErr:Module:13(114:155); file:external/openssl/crypto/asn1/asn1_lib.c ;Line:142;Function:ASN1_get_object`

so lead6 has the proper chain setup. I think swent1linux does as well, I think what is going is the node server is pointing at the wrong cert file.

I don't know how it is that nobody else reported this already.

**Comment by kgary** [comment]
The issue on swent1linux was that the wrong cert was neing used, need to use swent1linux_asu_edu_chained.cer not _cert

**Comment by kgary** [comment]
Use https://www.sslshopper.com/ssl-checker.html to validate certs in the future

**Comment by ChristianMurphy** [comment]
Please use the issue template in the future
