### ISSUE TITLE
PRP Logo

### ISSUE THREAD

**Issue by ChristianMurphy** [promisasu/Portal#345]
Currently the Portal is using Children's Health logo.
However this project is not officially funded by Children's Health or by Arizona State University.
It would be more appropriate for the project to have its own logo.

What should the PRP logo be?

**Comment by ChristianMurphy** [comment]
Here is a dry and boring icon.
Let's come up with something more interesting :stuck_out_tongue: 

![prp](https://cloud.githubusercontent.com/assets/3107513/14443654/6c69fcaa-fff5-11e5-8e52-c98343b16af5.png)

**Comment by ChristianMurphy** [comment]
Here is an alternative based off the [Caduceus](https://en.wikipedia.org/wiki/Caduceus)

![portalicon2](https://cloud.githubusercontent.com/assets/3107513/14445270/9406984e-0000-11e6-841e-44fb1d0dd6f8.png)

**Comment by poojaRal** [comment]
I like this one and would like to include this logo for the Portal Poster for Innovation Showcase
