### ISSUE TITLE
The date formats are not same in all the views of the portal

### ISSUE THREAD

**Issue by poojaRal** [promisasu/Portal#357]
**What did you do?**
Ran the portal.
**What did you expect to happen?**
Checked the date formats on dashboard, trial and patient view.
The date format must be the same through all the views
**What actually happened?**
Dashboard and Trial view display dates in 'YYYY-MM-DD' and patient view displays in 'MM-DD-YYYY' format.

**Comment by poojaRal** [comment]
Test the same on production server (lead6) and all the dates seem to have been redenred in 'MM-DD-YYYY' format for all the views.
This needs to be discussed once with @ChristianMurphy  and then fixed if required.

**Comment by ChristianMurphy** [comment]
This is definitely something that should be looked into.
Especially since we have had some inconsistency between dates displayed (`MM-DD-YYYY` and `YYYY-MM-DD`format) and date input fields (all `YYYY-MM-DD` format).
