### ISSUE TITLE
Merge Branches

### ISSUE THREAD

**Issue by ChristianMurphy** [promisasu/Portal#370]
Hey @AravindKv805 @chintanallstarz @mohitkm @sshirgao @TalabH!
Awesome work on improving and maintaining the promisasu portal! 🥇 
Its great to see you so involved in an open source project. 👍 

A slight concern I have is that the none of the changes have been merged to `master` in the past year, and code has been failing continuous integration for the past 3 months. 🚫 
Now is a great time to open a pull request from the most up-to-date branch to master, and work through the tech-debt built up over the past few months. 📈 

cc @kgary

**Comment by AravindKv805** [comment]
@ChristianMurphy Thanks a lot for the compliment. I agree that we have to merge all out code to master. We will work on it as soon as possible. Also, @TalabH is working on figuring out issues in Travis CI build and we will refactor our code once we have a report.
